_target_: src.models.layers.mlp.MlpCustom
linear1_cfg:
  _target_: src.models.layers.fastlinear.SparseLRLinear
  rank: 32
  sparse_cfg:
    _target_: src.models.layers.blockdiag_linear.BlockdiagLinear
    nblocks: 4
linear2_cfg: ${.linear1_cfg}
