_target_: src.models.layers.mlp.MlpCustom
linear1_cfg:
  _target_: src.models.layers.fastlinear.SparseLRLinear
  rank: 0.05
  sparse_cfg:
    _target_: src.models.layers.monarch_linear.MonarchLinear
    nblocks: 16
linear2_cfg: ${.linear1_cfg}
