
services:
  fly-service:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: fly:latest
    volumes:
      - .:/fly
      - /data:/data
      - ~/.cache/huggingface:/home/user/.cache/huggingface
    working_dir: /fly
    environment:
      - CUBLAS_WORKSPACE_CONFIG=:4096:8
      # - WANDB_API_KEY=
      # - HF_TOKEN=
    command: bash -c " git config --global --add safe.directory /fly && exec bash && chmod -R 777 /fly"

    stdin_open: true
    tty: true
    # gpu config
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ipc: host
    shm_size: '6g'
    container_name: peft
    ports:
      - "5050:5050"
