version: '3'

services:
  fly-service:
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
    image: fly:latest
    volumes:
      - .:/fly
      - /data:/data
    working_dir: /fly
    environment: 
      - WANDB_API_KEY=16d21dc747a6f33247f1e9c96895d4ffa5ea0b27
      - CUBLAS_WORKSPACE_CONFIG=:16:8
      - NVIDIA_VISIBLE_DEVICES=0,1,2,3
    command: bash -c " git config --global --add safe.directory /fly && exec bash"
        # rm /opt/conda/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py && ln -s /fly/src/models/modeling_roberta.py /opt/conda/lib/python3.8/site-packages/transformers/models/roberta/ "

    stdin_open: true
    tty: true 
    # gpu config 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ipc: host
    shm_size: '6g'
    container_name: peft
    ports:
      - "5050:5050"
      
# docker run -it --name peft \
#     -v "$(pwd)":/fly \
#     -w /fly \
#     -e WANDB_API_KEY=16d21dc747a6f33247f1e9c96895d4ffa5ea0b27 \
#     -e CUBLAS_WORKSPACE_CONFIG=:16:8 \
#     --gpus all \
#     --ipc=host \
#     --shm-size=6g \
#     -p 5050:5050 \
#     fly:latest \
#     bash -c "git config --global --add safe.directory /fly && exec bash"

