
services:
  fly-service:
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
    image: fly:latest
    volumes:
      - .:/fly
      - /data:/data
      - ~/.cache/huggingface:/home/user/.cache/huggingface
    working_dir: /fly
    environment: 
    # Remove before publishing the repo
      - WANDB_API_KEY=16d21dc747a6f33247f1e9c96895d4ffa5ea0b27
      - HF_TOKEN=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
      - CUBLAS_WORKSPACE_CONFIG=:4096:8
      # - https_proxy=http://127.0.0.1:7890/
      # - http_proxy=http://127.0.0.1:7890/
    command: bash -c " git config --global --add safe.directory /fly && exec bash"

    stdin_open: true
    tty: true 
    # gpu config 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ipc: host
    shm_size: '6g'
    container_name: peft
    ports:
      - "5050:5050"
#export https_proxy=http://127.0.0.1:7890/
#export http_proxy=http://127.0.0.1:7890/

# docker run -it --name peft \
#     -v "$(pwd)":/fly \
#     -w /fly \
#     -e WANDB_API_KEY=16d21dc747a6f33247f1e9c96895d4ffa5ea0b27 \
#     -e CUBLAS_WORKSPACE_CONFIG=:16:8 \
#     --gpus all \
#     --ipc=host \
#     --shm-size=6g \
#     -p 5050:5050 \
#     fly:latest \
#     bash -c "git config --global --add safe.directory /fly && exec bash"

