# @package model
_target_: src.models.layers.mlp.MlpCustom
linear1_cfg:
  _target_: src.models.layers.blocksparse_linear.BlockSparseLinear
  sparsity_config:
    _target_: src.models.layers.fastlinear.NinjaTurtleSparsityConfig
    block: 32
    window_size: 32
    stripes: 2
    step: 2
    gtoken: 64
  backend: dense
linear2_cfg: ${.linear1_cfg}
