
data_local: ./my-copy-c4/
data_remote: 

max_seq_len: 128
tokenizer_name: bert-base-uncased
mlm_probability: 0.30 

# Run Name
run_name: transformer-flash-attn

# Model
model:
  name: bert
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  model_config:
    num_attention_heads: 12 # bert-base default
    num_hidden_layers: 12 # bert-base default
    attention_probs_dropout_prob: 0.0 # This must be 0 for Flash Attention with triton to work
    max_position_embeddings: ${max_seq_len}
    use_glu_mlp: False

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.15 # We always evaluate at 15% masking for consistent comparison
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur # Warmup to the full LR for 6% of the training duration
  alpha_f: 0.02 # Linearly decay to 0.02x the full LR by the end of the training duration

optimizer:
  name: decoupled_adamw
  lr: 5.0e-4 # Peak learning rate
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-5 # Amount of weight decay regularization

algorithms:
  fused_layernorm: {}

max_duration: 286720000sp # Subsample the training data for ~275M samples
eval_interval: 2000ba
global_train_batch_size: 4096

# System
seed: 17
device_eval_batch_size: 128
device_train_microbatch_size: 128
# device_train_microbatch_size: auto
precision: amp_bf16

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}

# (Optional) W&B logging
# loggers:
#   wandb:
#     project:     # Fill this in
#     entity:      # Fill this in

# (Optional) Checkpoint to local filesystem or remote object store
save_interval: 7000ba
save_num_checkpoints_to_keep: 10  
save_folder: ./local-bert-checkpoints/{run_name} 
