# @package model
mlp_cfg:
  _target_: src.models.layers.mlp.MlpCustom
  linear1_cfg:
    _target_: src.models.layers.fastlinear.SparseLRLinear
    rank: 32
    sparse_cfg:
      _target_: src.models.layers.blocksparse_linear.BlockSparseLinear
      sparsity_config:
        _target_: src.models.layers.fastlinear.NinjaTurtleSparsityConfig
        block: 16
        window_size: 16
        stripes: 1
        step: 2
        gtoken: 16
  linear2_cfg: ${.linear1_cfg}
