defaults:
  - _self_
  - swinmlpmodel: swin-t-c24

_target_: src.models.swin_mlp.SwinMLP
img_size: ${datamodule.image_size}
patch_size: 4
in_chans: 3
num_classes: 1000
embed_dim: 96
depths: [2, 2, 6, 2]
num_heads: [3, 6, 12, 24]
window_size: 7
mlp_ratio: 4.0
drop_rate: 0.0
drop_path_rate: 0.1
ape: False
patch_norm: True
