_target_: src.models.attention.linear_attention.LinearAttention
# Embed dimension is model.mha_cfg.kdim if available, otherwise model.d_model
query_dims: ${eval:${oc.select:model.mha_cfg.kdim, ${model.d_model}} // ${model.n_head}}
