_target_: src.models.attention.sblocal_attention.SBLocalAttention
local_context: ???
# Embed dimension is model.mha_cfg.kdim if available, otherwise model.d_model
dim_heads: ${eval:${oc.select:model.mha_cfg.kdim, ${model.d_model}} // ${model.n_head}}
