_target_: src.datamodules.aan.AAN

data_dir: ${oc.env:DATA_DIR,${data_dir}}/aan/tsv_data # data_dir is specified in config.yaml
cache_dir: ${oc.env:DATA_DIR,${data_dir}}/aan/cache
max_length: 4000
shuffle: True
batch_size: 32
__train_len: 147086
