_target_: src.datamodules.imagenet.ImagenetDataModule

data_dir: ${oc.env:DATA_DIR,${data_dir}}  # data_dir is specified in config.yaml
shuffle: True
batch_size: 256
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 8
pin_memory: True
__train_len: 1281167
