_target_: src.datamodules.imagenet.Imagenet21kPDataModule

data_dir: ${oc.env:DATA_DIR,${data_dir}}  # data_dir is specified in config.yaml
shuffle: True
batch_size: 256
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 8
pin_memory: True
__train_len: 11060223
__num_classes: 10450
