_target_: src.datamodules.language_modeling.WikiText103
data_dir: ${oc.env:DATA_DIR,${data_dir}}/wikitext-103 # data_dir is specified in config.yaml
vocab_type: word
batch_size: 32  # per GPU
max_length: 192
roll_seed: 2357
batch_first: True
__train_len: ${div_up:${eval:103227021 - 1}, ${.max_length}}
