_target_: src.datamodules.language_modeling_hf.LMDataModule
dataset_name: wikitext
dataset_config_name: wikitext-2-raw-v1
tokenizer_name: gpt2
cache_dir: ${oc.env:DATA_DIR,${data_dir}}/wikitext-2/cache
max_length: 1024
add_eos: False
batch_size: 8  # per GPU
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 4  # For preprocessing only
shuffle: True
__train_len: ${div_up:2391884, ${.block_size}}
