# @package model
t2tattn1_cfg:
  _target_: src.models.attention.smyrf_attention.SmyrfAttention
  # seqlen = 3136, and we want to use 1/32 of the memory
  q_cluster_size: 49
  k_cluster_size: ${.q_cluster_size}
  n_hashes: 2
t2tattn2_cfg:
  _target_: ${..t2tattn1_cfg._target_}
  # seqlen = 784, and we want to use 1/32 of the memory
  q_cluster_size: 12
  k_cluster_size: ${.q_cluster_size}
  n_hashes: 2
